export interface MoodLog {
    id?: string; // Auto-generated by DB
    user_id: string;
    timestamp: string | Date; // ISO string or Date object
    mood_rating: number; // e.g., 1 (Very Low) to 5 (Very High)
    energy_rating: number; // e.g., 1 (Very Low) to 5 (Very High)
    notes?: string | null; // Optional context or journal entry
}

// Optional: Define constants for rating labels if needed elsewhere
export const MOOD_LABELS: { [key: number]: string } = {
    1: 'Very Low',
    2: 'Low',
    3: 'Neutral',
    4: 'High',
    5: 'Very High',
};

export const ENERGY_LABELS: { [key: number]: string } = {
    1: 'Very Low',
    2: 'Low',
    3: 'Neutral',
    4: 'High',
    5: 'Very High',
}; 