#!/bin/bash

# Script to help enable Safari Developer Tools (manual instructions)

echo "==================================================================="
echo "            Safari Developer Tools Setup Instructions              "
echo "==================================================================="
echo ""
echo "Since Safari preferences may require user interaction to modify,"
echo "please follow these steps manually to enable Developer Tools:"
echo ""
echo "1. Open Safari (opening it for you now)"
open -a Safari

echo ""
echo "2. In Safari, go to Safari > Settings..."
echo "   (In the top menu bar, click on 'Safari', then click 'Settings...')"
echo ""
echo "3. Click on the 'Advanced' tab"
echo ""
echo "4. Check the box that says 'Show Develop menu in menu bar'"
echo ""
echo "5. Close the Settings window"
echo ""
echo "6. Verify that 'Develop' appears in the menu bar between 'Bookmarks' and 'Window'"
echo ""
echo "7. To open Web Inspector once enabled:"
echo "   - Press Option+Command+I"
echo "   - Or select Develop > Show Web Inspector from the menu"
echo ""
echo "8. After setting up, you can use these scripts for development:"
echo "   - ./scripts/dev-safari.sh (start server and open Safari)"
echo "   - ./scripts/check-safari-errors.sh (check for console errors)"
echo "   - ./scripts/check-safari-network.sh (check for network errors)"
echo ""
echo "==================================================================="
echo ""
echo "Press Enter when you've completed these steps..."
read -p "" 